<?php
namespace App\Constants;

class GlosaTransaccion
{
    const CREDITO_DESDE_BILLETERA = 'SE ACREDITÓ A LA CAUSA DESDE LA BILLETERA GENERAL';
    const CREDITO_DESDE_CAUSA = 'SE ACREDITÓ A LA CAUSA DESDE OTRA CAUSA';
    const DEBITO_POR_TRASPASO = 'SE DEBITÓ POR TRASPASO A OTRA CAUSA';
    const DEBITO_POR_DEVOLUCION_A_BILLETERA_GRAL = 'SE DEBITÓ POR DEVOLUCIÓN A BILLETERA GENERAL';
    //Transacciones de Billetera general
    const DEBITO_DESDE_BILLETERA_POR_TRANSFERENCIA_A_CAUSA = 'SE DEBITÓ DE LA BILLETERA GENERAL POR TRANSFERENCIA A LA CAUSA';
    const CREDITO_DEPOSITO_A_BILLETERA = 'SE ACREDITÓ A LA BILLETERA GENERAL POR CONCEPTO DE DEPOSITO';
    const DEBITO_POR_COMPRA_DEL_PAQUETE = 'SE DEBITÓ POR COMPRA DEL PAQUETE';
    const CREDITO_DEVOLUCION_DE_CAUSA = 'SE ACREDITÓ A LA BILLETERA GENERAL POR DEVOLUCIÓN DE SALDO DE LA CAUSA';
}
