<?php
namespace App\Constants;

class GlosaTransaccion
{
    const CREDITO_DESDE_BILLETERA = 'SE ACREDITÓ A LA CAUSA DESDE LA BILLETERA';
    const CREDITO_DESDE_CAUSA = 'SE ACREDITÓ A LA CAUSA DESDE OTRA CAUSA';
    const DEBITO_POR_TRASPASO = 'SE DEBITÓ POR TRASPASO A OTRA CAUSA';
    //Transacciones de Billetera personal
    const DEBITO_DESDE_BILLETERA_POR_TRANSFERENCIA_A_CAUSA = 'SE DEBITÓ DE BILLETERA POR TRANSFERENCIA A CAUSA';
    const CREDITO_DEPOSITO_A_BILLETERA = 'SE ACREDITÓ A LA BILLETERA POR CONCEPTO DE DEPOSITO';
    const DEBITO_POR_COMPRA_DEL_PAQUETE = 'SE DEBITÓ POR COMPRA DEL PAQUETE';
}
