<?php
namespace App\Constants;

class GlosaTransaccion
{
    const CREDITO_DESDE_BILLETERA = 'SE ACREDITÓ A LA CAUSA DESDE LA BILLETERA';
    const CREDITO_DESDE_CAUSA = 'SE ACREDITÓ A LA CAUSA DESDE OTRA CAUSA';
    const DEBITO_POR_TRASPASO = 'SE DEBITÓ POR TRASPASO A OTRA CAUSA';
    const DEBITO_DESDE_BILLETERA_POR_TRANSFERENCIA_A_CAUSA = 'SE DEBITÓ DE BILLETERA POR TRANSFERENCIA A CAUSA';
}
